import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import "./globals.css";
import { SESSION_COOKIE_NAME, verifyAdminSessionToken } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(SESSION_COOKIE_NAME)?.value;
  const secret = process.env.AUTH_SECRET;
  const isAuthed = Boolean(token && secret && verifyAdminSessionToken(token, secret));

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full bg-white border-b border-zinc-200 px-4 py-3 flex justify-between items-center shadow-sm">
          <div className="font-bold text-xl tracking-tight text-indigo-600">Nusuk Scraper</div>
          <div className="flex items-center gap-3">
            {isAuthed ? (
              <form action="/api/auth/logout" method="post">
                <button
                  type="submit"
                  className="rounded-md bg-zinc-900 px-3 py-1.5 text-sm font-semibold text-white hover:bg-zinc-800"
                >
                  Logout
                </button>
              </form>
            ) : (
              <Link
                href="/login"
                className="rounded-md border border-zinc-300 bg-white px-3 py-1.5 text-sm font-semibold text-zinc-900 hover:bg-zinc-50"
              >
                Login
              </Link>
            )}
          </div>
        </header>
        <main className="flex-1 bg-zinc-50">
          {children}
        </main>
      </body>
    </html>
  );
}
